### ISSUE TITLE
Middle click UI is silly

### ISSUE THREAD

**Issue by rubenwardy** [MiJyn/mijyn.github.com#1]
* You can't middle click links
* It is unintuitive, when it doesn't need to be - you have to tell the user how to use the site

Sure, it's interesting, but only for the developer.
Sorry for being a bit cynical.

**Comment by MiJyn** [comment]
* I agree, that _is_ annoying, but links are target=_blank, so you can just click normally
 * True, but it's only one instruction .... so many websites are self-similar and boring =p

Thanks for the comment though, you're right, and I'll add an option so that the user can choose between this and the traditional way of scrolling (also the interface for mobiles and tablets) and maybe default it to the traditional way =)

I'm not planning on using this for an actual project website, that'd be ridiculous xD I treat my homepage like my ideal art website thingymajigie, so that's why I have that thing =p

**Comment by MiJyn** [comment]
Oh! Also, read the logs (was curious as to why both you and calinou wrote issues within the same minute xD), and you can use right click instead of middle, and for mobile devices, it works like a traditional website (also, even in the desktop mode, you can scroll using the scroll wheel) =)

**Comment by rubenwardy** [comment]
While it isn't practical on a real website, it is a rather interesting/cool design, like rotating the lock on a submarine door. I looked up how you did it.

When I said "sucks", I meant in terms of user experience, you had to move the mouse in a circle a lot - I am a big fan of minimalism and intuitive interfaces.

**Comment by MiJyn** [comment]
Exactly, yeah, which is why I said I would never use it for anything else than a personal homepage (or an art website, if such a thing even exists =p).

I see ... you're talking about using a mouse in a circle, I take it? And yeah same =D
